name: Gitleaks-Docker Build-Trivy & Push

on:
  push:
    branches: [main]

jobs:
  # 🔍 1️⃣ Scan kode sumber dengan GitLeaks
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Install dan Jalankan GitLeaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
          verbose: true

  # 🏗️ 2️⃣ Build Docker Image jika kode bersih
  build-image:
    runs-on: ubuntu-latest
    needs: secret-scan  # Build hanya berjalan jika GitLeaks sukses
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Login ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image Docker
        run: docker build -t javiersosial/hello-world-gitaction:1.0 .

      - name: Save Docker Image ke File
        run: docker save -o image.tar javiersosial/hello-world-gitaction:1.0

      - name: Upload Docker Image untuk Scan
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  # 🔬 3️⃣ Scan Image dengan Trivy sebelum push ke Docker Hub
  scan-image:
    runs-on: ubuntu-latest
    needs: build-image  # Scan hanya berjalan jika build sukses
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Install Trivy
        run: |
          sudo apt-get install -y curl gnupg
          curl -fsSL https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo tee /etc/apt/trusted.gpg.d/trivy.asc > /dev/null
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Scan Docker Image dengan Trivy
        run: trivy image --exit-code 1 --severity CRITICAL,HIGH javiersosial/hello-world-gitaction:1.0

  # 🚀 4️⃣ Push Image ke Docker Hub jika Scan Trivy berhasil
  push-image:
    runs-on: ubuntu-latest
    needs: scan-image  # Push hanya berjalan jika Trivy scan sukses
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Push image Docker ke Docker Hub
        run: docker push javiersosial/hello-world-gitaction:1.0

